import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  // Main Menu
  {
    path: '',
    title: '-- Main Menu --',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: [''],
    submenu: [],
  },

  // Dashboard
  {
    path: '/home/dashboard',
    title: 'home',
    moduleName: 'logout',
    iconType: 'material-icons-two-tone',
    icon: 'dashboard',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [''],
    submenu: [],
  },

  // Approve
  {
    path: '',
    title: 'Approval',
    moduleName: 'approval',
    iconType: 'material-icons-two-tone',
    icon: 'done_all',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [''],
    submenu: [
      {
        path: '/approval/approveteller',
        title: 'Approve Teller',
        moduleName: 'approval',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/approval/approveuser',
        title: 'Approve User',
        moduleName: 'approval',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/approval/approverole',
        title: 'Approve Role',
        moduleName: 'approval',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },

  // User
  {
    path: '',
    title: 'User Management',
    moduleName: 'usermanagement',
    iconType: 'material-icons-two-tone',
    icon: 'account_circle',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [''],
    submenu: [
      {
        path: '/usermanagement/allusers',
        title: 'All Users',
        moduleName: 'usermanagement',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/usermanagement/approveusers',
      //   title: 'Approve User',
      //   moduleName: 'usermanagement',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
    ],
  },

  // Roles
  {
    path: '',
    title: 'Role Management',
    moduleName: 'rolemanagement',
    iconType: 'material-icons-two-tone',
    icon: 'equalizer',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [''],
    submenu: [
      {
        path: '/rolemanagement/allroles',
        title: 'All Roles',
        moduleName: 'rolemanagement',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      // {
      //   path: '/rolemanagement/approveroles',
      //   title: 'Approve Roles',
      //   moduleName: 'rolemanagement',
      //   iconType: '',
      //   icon: '',
      //   class: 'ml-menu',
      //   groupTitle: false,
      //   badge: '',
      //   badgeClass: '',
      //   role: [''],
      //   submenu: [],
      // },
    ],
  },

  // Application
  {
    path: '/application/applications',
    title: 'Applications',
    moduleName: 'application',
    iconType: 'material-icons-two-tone',
    icon: 'nfc',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [''],
    submenu: [],
  },

  // Branch
  {
    path: '',
    title: 'Branches',
    moduleName: 'branch',
    iconType: 'material-icons-two-tone',
    icon: 'usb',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [''],
    submenu: [
      {
        path: '/branch/tellers',
        title: 'Tellers ',
        moduleName: 'branch',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/branch/branches',
        title: 'Branches',
        moduleName: 'branch',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },

  // Audit Log
  {
    path: '/auditlog/auditlogs',
    title: 'Audit Logs',
    moduleName: 'auditlog',
    iconType: 'material-icons-two-tone',
    icon: 'library_books',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [''],
    submenu: [],
  },

  // Transaction Log
  {
    path: '/transactionlog/transactionlogs',
    title: 'Transaction Logs',
    moduleName: 'transactionlog',
    iconType: 'material-icons-two-tone',
    icon: 'timeline',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: [''],
    submenu: [],
  },
];
